### ISSUE TITLE
DEMETER-AIM can't parse

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#211]
## To reproduce 
```
bin/ncbo_ontology_process -o DEMETER-AIM 
```

## Result 
```
Processing the following tasks: {:process_rdf=>true, :index_search=>true, :index_properties=>true, :run_metrics=>true, :process_annotator=>true, :diff=>true, :params=>nil} on ontologies: ["DEMETER-AIM"]
Processing details are logged to STDOUT
I, [2022-02-14T11:56:26.156338 #15459]  INFO -- : Logging parsing output to /srv/ontoportal/data/repository/DEMETER-AIM/5/parsing.log
I, [2022-02-14T11:56:26.156532 #15459]  INFO -- : ["Starting to process http://data.bioontology.org/ontologies/DEMETER-AIM/submissions/5"]
I, [2022-02-14T11:56:26.181187 #15459]  INFO -- : ["Starting to process DEMETER-AIM/submissions/5"]
I, [2022-02-14T11:56:26.307410 #15459]  INFO -- : ["deleting old owlapi.xrdf .."]
I, [2022-02-14T11:56:26.307840 #15459]  INFO -- : ["deleted"]
I, [2022-02-14T11:56:26.322545 #15459]  INFO -- : ["Java call [java -DentityExpansionLimit=2500000 -Xmx10240M -jar /srv/ontoportal/ncbo_cron_deployments/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-ac4a68542c33/bin/owlapi-wrapper.jar -m /srv/ontoportal/data/repository/DEMETER-AIM/5/demeterAgriProfile_v2.0.ttl -o /srv/ontoportal/data/repository/DEMETER-AIM/5 -r true]"]
I, [2022-02-14T11:59:48.038658 #15459]  INFO -- : ["2022-02-14T11:56:26 [main] INFO  o.s.n.o.OntologyParserCommand - Parsing invocation with values: ParserInvocation [inputRepositoryFolder=null, outputRepositoryFolder=/srv/ontoportal/data/repository/DEMETER-AIM/5, masterFileName=/srv/ontoportal/data/repository/DEMETER-AIM/5/demeterAgriProfile_v2.0.ttl, invocationId=0, parserLog=, userReasoner= true]\n\n2022-02-14T11:56:26 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - executor ...\n\n2022-02-14T11:56:27 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Input repository folder is null. Unique file being parsed.\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.binary.BinaryRDFParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.n3.N3ParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.nquads.NQuadsParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.ntriples.NTriplesParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.rdfjson.RDFJSONParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.jsonld.JSONLDParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.trix.TriXParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.turtle.TurtleParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.rdf4j.rio.RDFParserRegistry - Registered service class org.eclipse.rdf4j.rio.trig.TriGParserFactory\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.DatatypeHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.datatypes.XMLSchemaDatatypeHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.DatatypeHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.datatypes.RDFDatatypeHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.DatatypeHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.datatypes.DBPediaDatatypeHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.DatatypeHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.datatypes.VirtuosoGeometryDatatypeHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.DatatypeHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.datatypes.GeoSPARQLDatatypeHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.LanguageHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.languages.RFC3066LanguageHandler\n\n2022-02-14T11:56:27 [main] DEBUG o.e.r.rio.LanguageHandlerRegistry - Registered service class org.eclipse.rdf4j.rio.languages.BCP47LanguageHandler\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Calculating metrics for /srv/ontoportal/data/repository/DEMETER-AIM/5/demeterAgriProfile_v2.0.ttl\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Finished metrics calculation for /srv/ontoportal/data/repository/DEMETER-AIM/5/demeterAgriProfile_v2.0.ttl in 2 milliseconds\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Generated metrics CSV file for /srv/ontoportal/data/repository/DEMETER-AIM/5/demeterAgriProfile_v2.0.ttl\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Ontology document format: org.semanticweb.owlapi.formats.RioTurtleDocumentFormat\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isPrefixOWLOntologyFormat: true\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isOBO: false\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Serializing ontology in RDF ...\n\n2022-02-14T11:59:47 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Serialization done!\n\n2022-02-14T11:59:47 [main] INFO  o.s.n.o.OntologyParserCommand - Parse result: true\n\n2022-02-14T11:59:47 [main] INFO  o.s.n.o.OntologyParserCommand - Output triples in: {}/srv/ontoportal/data/repository/DEMETER-AIM/5/owlapi.xrdf\n\n2022-02-14T11:59:47 [main] INFO  o.s.n.o.OntologyParserCommand - Finished parsing!\n"]
I, [2022-02-14T11:59:48.039161 #15459]  INFO -- : ["OWLAPI Java command: parsing finished successfully."]
I, [2022-02-14T11:59:48.039346 #15459]  INFO -- : ["Output size 6157 in `/srv/ontoportal/data/repository/DEMETER-AIM/5/owlapi.xrdf`"]
I, [2022-02-14T11:59:48.039648 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriCommon/2.0"]
I, [2022-02-14T11:59:48.039694 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriFeature/2.0"]
I, [2022-02-14T11:59:48.039724 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriCrop/2.0"]
I, [2022-02-14T11:59:48.039803 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriIntervention/2.0"]
I, [2022-02-14T11:59:48.039834 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriAlert/2.0"]
I, [2022-02-14T11:59:48.039861 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriProduct/2.0"]
I, [2022-02-14T11:59:48.039893 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriProperty/2.0"]
I, [2022-02-14T11:59:48.039919 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriSystem/2.0"]
I, [2022-02-14T11:59:48.039948 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/agriPest/2.0"]
I, [2022-02-14T11:59:48.039978 #15459]  INFO -- : ["OWL_IMPORT_MISSING: https://w3id.org/demeter/agri/farmAnimal/2.0"]
I, [2022-02-14T11:59:48.132301 #15459]  INFO -- : ["Triples /srv/ontoportal/data/repository/DEMETER-AIM/5/owlapi.xrdf appended in <http://data.bioontology.org/ontologies/DEMETER-AIM/submissions/5>"]
I, [2022-02-14T11:59:48.140827 #15459]  INFO -- : ["Extraction metadata from ontology https://w3id.org/demeter/agri"]
I, [2022-02-14T11:59:51.629986 #15459]  INFO -- : ["Additional metadata extracted."]
I, [2022-02-14T11:59:51.633708 #15459]  INFO -- : ["Default metadata set."]
E, [2022-02-14T11:59:51.868532 #15459] ERROR -- : ["Empty page encountered. Retrying 1 times..."]
E, [2022-02-14T11:59:53.872788 #15459] ERROR -- : ["Empty page encountered. Retrying 2 times..."]
E, [2022-02-14T11:59:55.877130 #15459] ERROR -- : ["Empty page encountered. Retrying 3 times..."]
E, [2022-02-14T11:59:57.881365 #15459] ERROR -- : ["Empty page encountered. Retrying 4 times..."]
E, [2022-02-14T11:59:59.885626 #15459] ERROR -- : ["Empty page encountered. Retrying 5 times..."]
E, [2022-02-14T12:00:01.890710 #15459] ERROR -- : ["Empty page encountered. Retrying 6 times..."]
E, [2022-02-14T12:00:03.896136 #15459] ERROR -- : ["Empty page encountered. Retrying 7 times..."]
E, [2022-02-14T12:00:05.908722 #15459] ERROR -- : ["Empty page encountered. Retrying 8 times..."]
E, [2022-02-14T12:00:07.914202 #15459] ERROR -- : ["Empty page encountered. Retrying 9 times..."]
E, [2022-02-14T12:00:09.942561 #15459] ERROR -- : ["Empty page encountered. Retrying 10 times..."]
E, [2022-02-14T12:00:11.946357 #15459] ERROR -- : ["Empty page 1 of 1 persisted after retrying 10 times. Missing Labels Generation of 5 aborted..."]
E, [2022-02-14T12:00:12.576583 #15459] ERROR -- : Failed, exception: RuntimeError: Empty page 1 of 1 persisted after retrying 10 times. Missing Labels Generation of 5 aborted...
/srv/ontoportal/ncbo_cron_deployments/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-ac4a68542c33/lib/ontologies_linked_data/models/ontology_submission.rb:1374:in `block in loop_classes'
/usr/local/rbenv/versions/2.6.9/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/srv/ontoportal/ncbo_cron_deployments/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-ac4a68542c33/lib/ontologies_linked_data/models/ontology_submission.rb:1328:in `loop_classes'
/srv/ontoportal/ncbo_cron_deployments/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-ac4a68542c33/lib/ontologies_linked_data/models/ontology_submission.rb:1809:in `process_submission'
/srv/ontoportal/ncbo_cron_deployments/releases/20220124143731/lib/ncbo_cron/ontology_submission_parser.rb:193:in `process_submission'
bin/ncbo_ontology_process:98:in `block in <main>'
bin/ncbo_ontology_process:81:in `each'
bin/ncbo_ontology_process:81:in `<main>'
```

**Comment by jonquet** [comment]
We had such an issues resolving the imports in the past with DEMETER-AIM. But this was solved a fully working. 

The current file opens in Protégé and imports are localized properly. 
I am suspecting a OWL-API version discrepancy. 

Just produced with Protégé and loaded a RDF/XML version to check if this one parse in AgroPortal.

**Comment by syphax-bouazzouni** [comment]
It's not a parsing issue , in the logs we can see that the problem is in **"Empty page 1 of 1 persisted after retrying 10 times. Missing Labels Generation of 5 aborted..."**

**Comment by syphax-bouazzouni** [comment]
Don't really know how, but by redoing a process (without touching to anything ) it worked.

**Comment by jonquet** [comment]
Certainly the dependencies (owl:imports) that were unreachable from our side during last attempt.
