### ISSUE TITLE
Problem to edit/update "main" ontology submission when a view is created

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#269]
We re-observe with LEXEAU and LEXEAU-FR the problem experience in the past with CROPUSAGE that the main ontology (LEXEAU) can't be updated or edited anymore once a view has been created (LEXEAU-FR). 

However, the view (LEXEAU-FR) can be edited/updated normally.

**Comment by syphax-bouazzouni** [comment]
## Ontologies API logs (srv/ontoportal/ontologies_api/current/unicorn.stderr)
```
127.0.0.1, 127.0.0.1 - fairness_admin [13/May/2022:09:48:32 +0200] "GET /ontologies/LEXEAU/submissions/9?include=all HTTP/1.0" 200 13844 1.0283
2022-05-13 09:48:32 - Goo::Base::AttributeNotLoaded - Attribute `views` is not loaded for http://data.bioontology.org/ontologies/LEXEAU. Loaded attribu
tes: #<Set: {:acronym, :name, :administeredBy, :group, :viewingRestriction, :doNotUpdate, :flat, :hasDomain, :summaryOnly, :acl, :viewOf, :ontologyType
}>.:
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/goo-7e18f1001dfc/lib/goo/base/settings/settings.rb:272:in `block in shape_
attribute'
        /srv/ontoportal/ontologies_api/releases/20220512075816/helpers/application_helper.rb:32:in `block in populate_from_params'
        /srv/ontoportal/ontologies_api/releases/20220512075816/helpers/application_helper.rb:27:in `each'
        /srv/ontoportal/ontologies_api/releases/20220512075816/helpers/application_helper.rb:27:in `populate_from_params'
        /srv/ontoportal/ontologies_api/releases/20220512075816/controllers/ontologies_controller.rb:103:in `block (2 levels) in <class:OntologiesContro
ller>'
```
## The issue
Attribute `views` is not includes in  https://github.com/ontoportal-lirmm/ontologies_api/blob/master/controllers/ontologies_controller.rb#L100

**Comment by syphax-bouazzouni** [comment]
Fixed by https://github.com/ncbo/ontologies_api/pull/86 and https://github.com/ncbo/ontologies_api_ruby_client/pull/10
