### ISSUE TITLE
Services gone down

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#274]
## Service Issue
The 02/06/2022, Tomcat was down 

![Image](https://user-images.githubusercontent.com/29259906/171823952-49fd087a-9ccf-4803-9d3b-397c1f71193c.png)

## UI issue
The services broken made the browse page and the detail page inaccessible. The cause may be the fairness exception that was not catched 
```
F, [2022-06-03T10:50:59.146921 #11450] FATAL -- :   
MultiJson::ParseError (unexpected character (after ) at line 1, column 1 [parse.c:769]):
  
app/helpers/fair_score_helper.rb:15:in `get_fairness_json'
app/helpers/fair_score_helper.rb:19:in `get_fair_score'
app/controllers/ontologies_controller.rb:408:in `summary'
app/controllers/ontologies_controller.rb:373:in `show'

```

**Comment by syphax-bouazzouni** [comment]
same as  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/8
