### ISSUE TITLE
Terms in AGROVOC are indexed but not browsable

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#304]
Report on support mailing list: 

When searching for keywords in AGROVOC, these can be found , however, when clicking the link for some of them (e.g. inoculation, nursery raising) an error message is returned. 
"We're sorry but something has gone wrong ..."

**Comment by jonquet** [comment]
I was able to reproduce the error. Indeed the term « Inoculation » is found by our index but then do not open in the Browser. 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/7379183/194641521-21ae534f-3b56-47d9-86c8-256b458bd16d.png">

**Comment by syphax-bouazzouni** [comment]
## Issue origin
The cause is this endpoint not working 

http://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_3879/tree 

### Log 

```ruby 

10.101.102.101, 127.0.0.1 - admin [12/Oct/2022:09:53:02 +0200] "GET /ontologies/AGROVOC/classes/http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_3879/tree HTTP/1.0" 500 30 0.2956
Class http://cat.aii.caas.cn/concept/23806 from http://data.bioontology.org/ontologies/AGROVOC/submissions/26 cannot load parents
2022-10-12 09:54:17 - Goo::Base::AttributeNotLoaded - Attribute `children` is not loaded for http://cat.aii.caas.cn/concept/23806. Loaded attributes: #<Set: {:submission}>.:
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/goo-d1d34dcf4554/lib/goo/base/settings/settings.rb:272:in `block in shape_attribute'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-b9a3395eeb24/lib/ontologies_linked_data/models/class.rb:381:in `block in tree'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-b9a3395eeb24/lib/ontologies_linked_data/models/class.rb:379:in `each'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-b9a3395eeb24/lib/ontologies_linked_data/models/class.rb:379:in `tree'
        /srv/ontoportal/ontologies_api/releases/20220725095641/controllers/classes_controller.rb:133:in `block (2 levels) in <class:ClassesController>'
```

**Comment by syphax-bouazzouni** [comment]
Fixed
